language: perl

install:
  - sudo apt-get update
  - sudo apt-get install libarchive-dev
  - cpanm -n Dist::Zilla
  - dzil authordeps --missing |cpanm -n
  - cpanm -n Alien::Libarchive
  - cpanm -n Test::CPAN::Changes Test::EOL Test::Fixme Test::NoTabs Test::Pod::Spelling::CommonMistakes Test::Spelling Test::Strict Test::Version || true
  - cpanm -n Pod::Abstract
  - cpanm -n Mojolicious
  # workaround for gh#31 (Archive::Libarchive::XS)
  - cpanm -n http://cpan.metacpan.org/authors/id/R/RJ/RJBS/Mixin-Linewise-0.102.tar.gz
  - git clone https://github.com/merrilymeredith/p5-FFI-Sweet.git && cd p5-FFI-Sweet && dzil authordeps --missing |cpanm -n && dzil install && cd .. && rm -rf p5-FFI-Sweet
  - git clone https://github.com/plicease/FFI-Util.git && cd FFI-Util && dzil authordeps --missing |cpanm -n && dzil install && cd .. && rm -rf FFI-Util
  - git clone https://github.com/plicease/Archive-Libarchive-$ARCHIVE_LIBARCHIVE_ANY.git && cd Archive-Libarchive-$ARCHIVE_LIBARCHIVE_ANY && dzil authordeps --missing |cpanm -n && dzil install --install-command 'cpanm -n .' && cd .. && rm -rf Archive-Libarchive-$ARCHIVE_LIBARCHIVE_ANY

perl:
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
  - "5.19"

script: dzil test -v

env:
  - ARCHIVE_LIBARCHIVE_ANY=XS  ALIEN_LIBARCHIVE=system
  - ARCHIVE_LIBARCHIVE_ANY=FFI ALIEN_LIBARCHIVE=system
  - ARCHIVE_LIBARCHIVE_ANY=XS  ALIEN_LIBARCHIVE=share
  - ARCHIVE_LIBARCHIVE_ANY=FFI ALIEN_LIBARCHIVE=share
